### ISSUE TITLE
Visualize distribution of studies accross samples

### ISSUE THREAD

**Issue by mziegler** [deweylab/MetaSRA-website-frontend#11]
To what extent are the search-result samples bunched up in just a few big studies?

- Histogram?
- Sort studies by most-samples?  (This would be more useful if we decide only to show studies at first, and then make the user click something to drill down to samples.)

**Comment by mziegler** [comment]
@cndewey @mbernste How well do you feel this problem is addressed by the updated design, with more compact view of the studies and studies sorted by greatest-number-of-samples?

**Comment by mbernste** [comment]
I think what you propose here would address the "results summary" goal.  I don't know how useful more sophisticated visualizations would be. At the very least, I don't think this should be prioritized in the remaining month
