### ISSUE TITLE
Change tagline

### ISSUE THREAD

**Issue by mziegler** [deweylab/MetaSRA-website-frontend#13]
We need a simple, concise, 1-sentence description of what the website does.  Try to sound cool and impressive without exaggerating.

Currently set to "Easily search for human sequence-read data"

**Comment by mbernste** [comment]
Maybe:
- Easily search the Sequence Read Archive 
- Easily search for human sequencing data

**Comment by mziegler** [comment]
Just going to remove the tagline because it's become redundant
