### ISSUE TITLE
OR term field

### ISSUE THREAD

**Issue by mziegler** [deweylab/MetaSRA-website-frontend#15]
Add an "OR" ontology-term field to complement the "AND" and "NOT" fields.

Is this feature worth the interface-clutter that it would add?  Can we think of use cases?

**Comment by mziegler** [comment]
Can we think of use cases for this?  @cndewey @mbernste

**Comment by mbernste** [comment]
Perhaps the user interviews will help illuminate this; however, my hunch is that this is not a feature we should prioritize.  I feel that most "OR" queries can be done with multiple searches.
