### ISSUE TITLE
Add examples to home page

### ISSUE THREAD

**Issue by mziegler** [deweylab/MetaSRA-website-frontend#16]
When there are no search terms entered, show some examples of what you might search for.  Try to show off a broad range of functionality.

We can get some examples from user-test subjects.

**Comment by mziegler** [comment]
@cndewey @mbernste Suggestions?

**Comment by mbernste** [comment]
Some examples that come to mind:

- Goal find healthy, liver tissue. 
-- Require: "Liver". 
-- Exclude: "Disease", "Treatment"
-- Sample type: Tissue

- Goal find healthy, primary T-cells:
-- Require: "T cell". 
-- Exclude: "Disease", "Treatment"
-- Sample type: Primary cell

- Goal find glioblastoma samples:
-- Require: "brain", "glioblastoma".

**Comment by mziegler** [comment]
These are good.  I'll put these on the website.

I think 3 is about the right number of examples to show - if it's many more than that then people won't read them.
