### ISSUE TITLE
Download expression matrix for results list

### ISSUE THREAD

**Issue by mziegler** [deweylab/MetaSRA-website-frontend#18]
This would actually be pretty hard, as neither Recount2 or Expression Atlas have API’s (documented or undocumented) that would allow this.  We would have to come up with something really hacky, or download their whole datasets and serve it ourselves, updating it every so often.  It’d be much easier to link users to data for individual samples.

**Comment by mbernste** [comment]
If Recount2 nor the Expression Atlas have documented API's then perhaps we should not deal with this for now.  Links to individual samples might be fine enough in the meanwhile.

**Comment by mziegler** [comment]
Not going to do this for now.  Maybe we can generate some R code to download studies from Recount?
