### ISSUE TITLE
Server returns 500 error with too-broad terms

### ISSUE THREAD

**Issue by mziegler** [deweylab/MetaSRA-website-frontend#19]
When you enter a really broad term with many many associated samples, like "multicellular anatomical structure," MongoDB exceeds its memory limit and the server issues a 500 error.

Ways we could deal with this:
- increase the memory limit (might cause trouble)
- remove terms from the autocomplete that are associated with too many samples

It's hard for me to imagine what the use cases would be for queries like these.

**Comment by mbernste** [comment]
How many samples causes this error?  

I think if the number of samples returned is too large, we can can remove them from autocomplete.

**Comment by mziegler** [comment]
Actually I'm just going to catch that specific memory error from the database, and show an error message saying to choose a more specific query.

**Comment by mziegler** [comment]
Search "anatomical entity" to test
