### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by mbernste** [deweylab/MetaSRA-website-frontend#2]
Before we launch the new version of the website, we'll want to get Google analytics hooked up to the website.  A few things we should have tracking before launch:

1. Number of page hits
2. Number of downloads of the database files 

A few things that would be great to track, but aren't a priority for launch:

1. Number of searches
2. Number of downloads of individual search results

**Comment by mziegler** [comment]
I think I have the front-end set up to log searches, but need to verify from the GA interface that the pageviews are being recieved.

GA has some special tools for search interfaces that we can set up using this guide:
https://support.google.com/analytics/answer/1012264?hl=en

Also, I think I can set it up to send pageviews to GA from the front-end if we decide not to do it via google tag manager for whatever reason.
