### ISSUE TITLE
Update logos to SVG, where possible

### ISSUE THREAD

**Issue by cndewey** [deweylab/MetaSRA-website-frontend#29]
On retina displays, lower resolution images can look blurry.  It's best if vector-based formats are used.  It would be great of the main MetaSRA logo could be changed to SVG.  The UW logo can be found in SVG here:

http://brand.wisc.edu/content/uploads/2016/11/uw-crest-web.zip

**Comment by mziegler** [comment]
Changed MetaSRA and UW logos to SVG.  There's no SVG logo for CPCP in the press kit.

**Comment by cndewey** [comment]
The 'A' of MetaSRA is not showing up in the logo (SVG bounding box issue?).  Also, the UW logo is no longer visible.

**Comment by mziegler** [comment]
What platform/browser are you using?  

Could you try opening http://metasra.biostat.wisc.edu/v2/assets/logo.svg and http://metasra.biostat.wisc.edu/v2/assets/uw-logo.svg to see if the images render correctly?

If those URL's don't work try http://metasra.biostat.wisc.edu/assets/logo.svg and http://metasra.biostat.wisc.edu/assets/uw-logo.svg

**Comment by cndewey** [comment]
![untitled](https://user-images.githubusercontent.com/593105/31637644-8673cc14-b284-11e7-93fb-fc8b1f5d1f32.png)

macOS 10.13 (High Sierra)
It looks like this in Safari, Chrome, and Firefox.

When I open the SVG in Adobe Illustrator, it looks like the visible area is smaller than the logo, cutting off the A.

**Comment by cndewey** [comment]
http://metasra.biostat.wisc.edu/v2/assets/uw-logo.svg 
renders correctly.

**Comment by mbernste** [comment]
That's how it appeared on mine as well. Seemed to be a retina display issue. We've fixed the issue on my machine. Do you want to try a hard refresh now?

**Comment by mziegler** [comment]
OK the MetaSRA logo should be fixed.  Had to export text as SVG shape.  Maybe your browser still trying to find the PNG UW logo?  Can you hard refresh?

**Comment by cndewey** [comment]
Looks good now!
