### ISSUE TITLE
Add text clarifying that only RNA-seq samples are currently in MetaSRA

### ISSUE THREAD

**Issue by cndewey** [deweylab/MetaSRA-website-frontend#31]
Either with a ? icon to the right of "Find human RNA-seq samples" and/or text on the About tab, it would be good to clarify that the current MetaSRA only contains RNA-seq samples, but that future releases will include samples from other assays.  Possible text would be:

"The MetaSRA currently annotates each human RNA-seq sample in the Sequence Read Archive (SRA) using standardized terms from biomedical ontologies.  Future releases of the MetaSRA will include samples from other species and assays."

**Comment by mziegler** [comment]
Added a ? icon and popup with your text, and added FAQ questions.
