### ISSUE TITLE
Ontology key rendering issue

### ISSUE THREAD

**Issue by mbernste** [deweylab/MetaSRA-website-frontend#39]
The colored circles that act as a color-key for the ontologies have a black dot in the centers (I assume they are bullet points that are not obscured by the colored circles).  This happens in both Safari and Chrome on my Mac.

![error](https://user-images.githubusercontent.com/5004419/31863155-23742084-b70f-11e7-80e9-3f9eb0fb55ae.png)

**Comment by mziegler** [comment]
Fixed in d8245c45a7e20884dc27b3e4781eb0efe3d89ff5
