### ISSUE TITLE
Clean-up and document database-update process

### ISSUE THREAD

**Issue by mziegler** [deweylab/MetaSRA-website-frontend#9]
Document the procedure for setting up the database.

**Comment by mziegler** [comment]
TODO: how to manage the ontolib dependency for python 3?  Should I just include the ported copy of ontolib in the metasra-backend repository?  Should I fork the not-yet-published ontolib library for the python3 port?  Should the python3 port be a part of the ontolib repository? @mbernste

**Comment by mbernste** [comment]
Do you mind sharing the Python 3 version of ontolib to me, then I can create a GitHub repo you can link to.  Would that work?

**Comment by mziegler** [comment]
Sounds good!  I've put the python3 code in /tier2/deweylab/scratch/ziegler/onto_lib_py3 (minus the obo subdirectory).
